## Training/Test sets

In [1]:
from random import randrange
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("~/Documents/BM/Curso DS/gender_classification_v7.csv",dtype='str',encoding = "ISO-8859-1")

In [3]:
dataset.describe()

long_hair forehead_width_cm forehead_height_cm nose_wide nose_long  \
count       5002              5002               5002      5002      5002   
unique         2                42                 21         2         2   
top            1                12                5.7         0         1   
freq        4350               168                306      2531      2541   

       lips_thin distance_nose_to_lip_long gender  
count       5002                      5002   5002  
unique         2                         2      2  
top            0                         0   Male  
freq        2535                      2506   2501

In [4]:
print("duplicados: ",dataset.duplicated().sum())

duplicados:  1769


In [5]:
clean_dataset = dataset.drop_duplicates()

In [6]:
clean_dataset.describe()

long_hair forehead_width_cm forehead_height_cm nose_wide nose_long  \
count       3233              3233               3233      3233      3233   
unique         2                42                 21         2         2   
top            1              11.9                6.3         1         1   
freq        2659               100                195      1734      1803   

       lips_thin distance_nose_to_lip_long gender  
count       3233                      3233   3233  
unique         2                         2      2  
top            1                         1   Male  
freq        1741                      1763   1783

In [7]:
def train_test_split_zero(dataset, split=0.80):
    train = list()
    train_size = split * len(dataset)
    dataset_copy = list(dataset)
    while len(train) < train_size:
        index = randrange(len(dataset_copy))
        train.append(dataset_copy.pop(index))
    return train, dataset_copy

In [8]:
data = clean_dataset.values.tolist()
train, test = train_test_split_zero(data)

In [9]:
pd.DataFrame(train).describe()

0     1     2     3     4     5     6     7
count   2587  2587  2587  2587  2587  2587  2587  2587
unique     2    42    21     2     2     2     2     2
top        1  14.1   6.3     1     1     1     1  Male
freq    2131    83   159  1394  1453  1395  1421  1441

In [10]:
pd.DataFrame(test).describe()

0     1    2    3    4    5    6     7
count   646   646  646  646  646  646  646   646
unique    2    42   21    2    2    2    2     2
top       1  13.5  5.5    1    1    1    1  Male
freq    528    27   49  340  350  346  342   342

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
train, test =train_test_split(clean_dataset,test_size=0.2)

In [13]:
pd.DataFrame(train).describe()

long_hair forehead_width_cm forehead_height_cm nose_wide nose_long  \
count       2586              2586               2586      2586      2586   
unique         2                42                 21         2         2   
top            1              11.8                5.8         1         1   
freq        2120                82                165      1380      1444   

       lips_thin distance_nose_to_lip_long gender  
count       2586                      2586   2586  
unique         2                         2      2  
top            1                         1   Male  
freq        1389                      1402   1419

In [14]:
pd.DataFrame(test).describe()

long_hair forehead_width_cm forehead_height_cm nose_wide nose_long  \
count        647               647                647       647       647   
unique         2                42                 21         2         2   
top            1                14                6.5         1         1   
freq         539                25                 47       354       359   

       lips_thin distance_nose_to_lip_long gender  
count        647                       647    647  
unique         2                         2      2  
top            1                         1   Male  
freq         352                       361    364

In [15]:
X = clean_dataset.iloc[:,:7]
y = clean_dataset.iloc[:,-1]

In [16]:
x_train,x_test,y_train,y_test =train_test_split(X,y,test_size=0.3)

In [17]:
x_train

long_hair forehead_width_cm forehead_height_cm nose_wide nose_long  \
3690         1              11.5                6.2         1         0   
1455         1              11.6                5.4         0         0   
1374         0                13                6.5         1         1   
1141         1              12.7                5.9         1         1   
1000         1              14.2                5.7         1         1   
...        ...               ...                ...       ...       ...   
2420         1              11.6                5.6         1         0   
716          1              13.3                6.1         1         1   
2393         1              14.3                6.6         1         1   
4266         1              13.6                6.6         1         1   
275          1              13.9                6.1         0         0   

     lips_thin distance_nose_to_lip_long  
3690         0                         0  
1455         0                         0  
1374         1                         1  
1141         1                         1  
1000         1                         1  
...        ...                       ...  
2420         0                         0  
716          1                         1  
2393         1                         1  
4266         1                         1  
275          0                         0  

[2263 rows x 7 columns]

In [18]:
x_test

long_hair forehead_width_cm forehead_height_cm nose_wide nose_long  \
3515         1              11.9                6.4         0         0   
3962         1              13.1                5.7         0         0   
2291         1              12.1                  7         1         1   
1622         1              12.1                6.5         0         0   
234          1              15.5                5.6         1         1   
...        ...               ...                ...       ...       ...   
1788         1              12.2                5.5         0         1   
815          1              11.9                6.3         1         1   
2593         1              14.9                6.3         1         1   
2482         1              13.7                6.9         0         1   
2797         0              14.8                5.6         1         1   

     lips_thin distance_nose_to_lip_long  
3515         1                         0  
3962         0                         0  
2291         1                         1  
1622         0                         0  
234          1                         1  
...        ...                       ...  
1788         0                         0  
815          1                         0  
2593         1                         1  
2482         1                         1  
2797         0                         1  

[970 rows x 7 columns]

In [19]:
y_train

3690    Female
1455    Female
1374      Male
1141      Male
1000      Male
         ...  
2420    Female
716       Male
2393      Male
4266      Male
275     Female
Name: gender, Length: 2263, dtype: object

## Training/Validation/Test sets

### Ejercicio

Generar los conjuntos de entrenamiento, validación y prueba en proporciones de 60%, 20% y 20% del dataset completo respectivamente

In [20]:
train, test_0 =train_test_split(clean_dataset,train_size=0.6)

In [21]:
test, val =train_test_split(test_0,train_size=0.5)

In [22]:
train

long_hair forehead_width_cm forehead_height_cm nose_wide nose_long  \
1488         0              12.6                6.2         1         0   
4536         0              11.9                5.4         0         0   
3939         1              15.3                5.1         1         1   
1486         1                13                5.3         0         0   
1349         1              14.1                6.2         0         0   
...        ...               ...                ...       ...       ...   
1461         1              11.5                  7         1         1   
2601         1              15.1                5.5         1         1   
2773         1              12.1                6.4         0         1   
3302         1              12.5                5.1         0         0   
1779         1              11.9                6.1         0         1   

     lips_thin distance_nose_to_lip_long  gender  
1488         0                         1  Female  
4536         0                         0  Female  
3939         1                         1    Male  
1486         0                         0  Female  
1349         0                         0  Female  
...        ...                       ...     ...  
1461         1                         1    Male  
2601         1                         1    Male  
2773         0                         0  Female  
3302         1                         0  Female  
1779         0                         0  Female  

[1939 rows x 8 columns]

In [23]:
val

long_hair forehead_width_cm forehead_height_cm nose_wide nose_long  \
164          1              14.6                6.2         1         1   
3303         1              12.9                5.4         0         0   
412          1              13.3                6.1         0         1   
2525         1              14.8                6.8         1         0   
4069         1                13                5.8         1         1   
...        ...               ...                ...       ...       ...   
1335         1                14                5.5         1         1   
3251         1                14                6.1         1         1   
4534         1              11.8                6.4         1         0   
517          1              14.3                5.5         0         0   
2222         1              15.2                6.9         1         1   

     lips_thin distance_nose_to_lip_long  gender  
164          1                         1    Male  
3303         1                         0  Female  
412          0                         0  Female  
2525         1                         1    Male  
4069         1                         1    Male  
...        ...                       ...     ...  
1335         0                         1    Male  
3251         0                         1    Male  
4534         1                         1    Male  
517          1                         0  Female  
2222         1                         1    Male  

[647 rows x 8 columns]

In [24]:
test

long_hair forehead_width_cm forehead_height_cm nose_wide nose_long  \
4256         0              14.3                5.9         0         0   
2210         1              13.7                5.4         0         0   
1906         0              12.1                5.7         1         1   
2820         1              12.1                6.1         0         0   
1588         1              12.4                5.5         1         1   
...        ...               ...                ...       ...       ...   
3742         1              13.1                6.5         1         1   
2462         0              13.4                6.9         1         1   
3022         0              15.2                6.7         1         1   
893          1              14.1                5.7         1         1   
1968         0              12.4                6.1         0         0   

     lips_thin distance_nose_to_lip_long  gender  
4256         0                         0  Female  
2210         1                         1  Female  
1906         1                         0    Male  
2820         0                         1  Female  
1588         1                         1    Male  
...        ...                       ...     ...  
3742         0                         1    Male  
2462         1                         1    Male  
3022         1                         0    Male  
893          1                         1    Male  
1968         0                         0  Female  

[647 rows x 8 columns]

## Cross validation 

In [25]:
from sklearn import svm
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score

In [26]:
X_data = X.to_numpy()
y_data = y.to_numpy()

In [27]:
model = svm.SVC()
scores = []

In [28]:
kf = KFold(n_splits=5, shuffle = True) 

for train_index, test_index in kf.split(clean_dataset):
    X_train, X_test = X_data[train_index], X_data[test_index] 
    y_train, y_test = y_data[train_index], y_data[test_index]
    
    model.fit(X_train,y_train)
    true_y = model.predict(X_test)
    accuracy = accuracy_score(true_y,y_test)
    scores = np.append(scores, accuracy)
    
    

In [29]:
scores

array([0.94435858, 0.9381762 , 0.9675425 , 0.95820433, 0.9504644 ])

In [30]:
from sklearn.model_selection import cross_val_score

In [31]:
model_2 = svm.SVC()
scores = cross_val_score(model_2, X_data, y_data, cv=6)
scores

array([0.94619666, 0.96289425, 0.94434137, 0.94990724, 0.94805195,
       0.95539033])

### Ejercicio

Usando el dataset "Boston" utilizando en la clase de Regresión Ridge y Lasso, aplicar la técnica de Cross validation a estos dos algoritmos y con 6 diferentes hiperparámetros lambda(alpha)

In [32]:
from sklearn import datasets
from sklearn.linear_model import Ridge, LinearRegression, Lasso
from sklearn.metrics import mean_squared_error

In [33]:
boston_X, boston_y = datasets.load_boston(return_X_y=True)

In [34]:
kf = KFold(n_splits=6, shuffle = True) 

alpha = 1.0
scores = []

for train_index, test_index in kf.split(boston_X):
    boston_X_train, boston_X_test = boston_X[train_index], boston_X[test_index] 
    boston_y_train, boston_y_test = boston_y[train_index], boston_y[test_index]
    
    model = Ridge(alpha)
    print("alpha: ",alpha)
    alpha = alpha + 1

    
    model.fit(boston_X_train,boston_y_train)
    boston_true_y = model.predict(boston_X_test)
    accuracy = mean_squared_error(boston_true_y,boston_y_test)
    scores = np.append(scores, accuracy)
    

    

alpha:  1.0
alpha:  2.0
alpha:  3.0
alpha:  4.0
alpha:  5.0
alpha:  6.0


In [35]:
scores

array([12.86601338, 17.27177688, 26.53675402, 31.62164052, 39.63028581,
       19.01100418])

In [36]:
from sklearn.model_selection import RepeatedKFold

In [37]:
rkf = RepeatedKFold(n_splits = 10, n_repeats = 5)

In [38]:
scores = []

In [39]:
clean_dataset.describe()

long_hair forehead_width_cm forehead_height_cm nose_wide nose_long  \
count       3233              3233               3233      3233      3233   
unique         2                42                 21         2         2   
top            1              11.9                6.3         1         1   
freq        2659               100                195      1734      1803   

       lips_thin distance_nose_to_lip_long gender  
count       3233                      3233   3233  
unique         2                         2      2  
top            1                         1   Male  
freq        1741                      1763   1783

In [40]:
model = svm.SVC()
scores = []

In [41]:
for train_index, test_index in rkf.split(clean_dataset):
    X_train, X_test = X_data[train_index], X_data[test_index] 
    y_train, y_test = y_data[train_index], y_data[test_index]
    
    
    model.fit(X_train,y_train)
    true_y = model.predict(X_test)
    accuracy = accuracy_score(true_y,y_test)
    scores = np.append(scores, accuracy)

In [42]:
scores

array([0.95061728, 0.9382716 , 0.95061728, 0.9628483 , 0.9380805 ,
       0.94427245, 0.96904025, 0.94736842, 0.95665635, 0.9628483 ,
       0.96296296, 0.9382716 , 0.9691358 , 0.97213622, 0.92879257,
       0.94736842, 0.97213622, 0.95665635, 0.96594427, 0.91021672,
       0.94753086, 0.96604938, 0.95061728, 0.9380805 , 0.95975232,
       0.96904025, 0.94117647, 0.95665635, 0.94117647, 0.94427245,
       0.94135802, 0.95987654, 0.96296296, 0.94736842, 0.93498452,
       0.94736842, 0.95356037, 0.9628483 , 0.95356037, 0.94736842,
       0.95061728, 0.97222222, 0.95987654, 0.95665635, 0.95356037,
       0.93498452, 0.9504644 , 0.95356037, 0.95356037, 0.94427245])